apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stg-donus-hpa
  namespace: donus
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stg-donus-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70