apiVersion: v1
kind: Service
metadata:
    name: donus
    namespace: donus
    labels:
        app: donus
        tier: frontend
spec:
    type: NodePort
    ports:
        - port: 3000
    selector:
        app: donus
        tier: frontend

---

apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
    name: stg-donus-service-backendconfig
    namespace: donus
spec:
    timeoutSec: 80000
    connectionDraining:
        drainingTimeoutSec: 3600 # time to complete connections
