apiVersion: v1
kind: ConfigMap
metadata:
  name: stg-donus-config
  namespace: donus
data:
  ENVIRONMENT: "develop"
  # Endpoints
  REACT_APP_HOST: "https://dev-backofficeapi.alfreddelivery.com/"
  IMAGE_APP_HOST: "https://dev-imageapi.alfreddelivery.com/"