apiVersion: apps/v1
kind: Deployment
metadata:
    name: stg-freight-deployment
    namespace: freight
    labels:
        app: freight
        tier: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: freight
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 2
            maxUnavailable: 1
    template:
        metadata:
            labels:
                app: freight
                tier: frontend
        spec:
            containers:
                - image: gcr.io/alfred-302520/stg-freight-api:0.1
                  #command: ["sleep 600"]
                  imagePullPolicy: IfNotPresent
                  name: freight
                  resources: 
                    limits:
                      cpu: 1000
                      memory: 1000Mi
                    requests:
                      cpu: 300m
                      memory: 300Mi           
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  envFrom:
                  - configMapRef:
                      name: stg-freight-config
                  env:
                      - name: SERVER_DBUSER
                        valueFrom:
                            secretKeyRef:
                                name: stg-credentials-freight
                                key: username
                      - name: SERVER_DBPASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: stg-credentials-freight
                                key: password                  
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 10