apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: freight-hpa
  namespace: freight
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: freight-deployment
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70