apiVersion: v1
kind: Service
metadata:
    name: freight
    namespace: freight
    labels:
        app: freight
        tier: frontend
spec:
    type: NodePort
    ports:
        - port: 8000
    selector:
        app: freight
        tier: frontend

---

apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
    name: freight-service-backendconfig
    namespace: freight
spec:
    timeoutSec: 80000
    connectionDraining:
        drainingTimeoutSec: 3600 # time to complete connections
