apiVersion: apps/v1
kind: Deployment
metadata:
    name: shopper-deployment
    namespace: shopper
    labels:
        app: shopper
        tier: frontend
spec:
    replicas: 3
    selector:
        matchLabels:
            app: shopper
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 2
            maxUnavailable: 1
    template:
        metadata:
            labels:
                app: shopper
                tier: frontend
        spec:
            containers:
                - image: gcr.io/alfred-302520/shopper-api:0.2
                  #command: ["sleep 600"]
                  imagePullPolicy: IfNotPresent
                  name: shopper
                  resources:
                    # limits:
                    #   cpu: 2000m
                    #   memory: 2000Mi
                    # requests:
                    #   cpu: 500m
                    #   memory: 300Mi                  
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  envFrom:
                  - configMapRef:
                      name: shopper-config
                  env:
                      - name: SERVER_DBUSER
                        valueFrom:
                            secretKeyRef:
                                name: credentials-shopper
                                key: username
                      - name: SERVER_DBPASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: credentials-shopper
                                key: password
                                         
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 10