apiVersion: v1
kind: Service
metadata:
    name: shopper
    namespace: shopper
    labels:
        app: shopper
        tier: frontend
spec:
    type: NodePort
    ports:
        - port: 8000
    selector:
        app: shopper
        tier: frontend

---

apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
    name: shopper-service-backendconfig
    namespace: shopper
spec:
    timeoutSec: 80000
    connectionDraining:
        drainingTimeoutSec: 3600 # time to complete connections
