apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shopper-hpa
  namespace: shopper
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: shopper-deployment
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70