apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stg-shopper-hpa
  namespace: shopper
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stg-shopper-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70