apiVersion: apps/v1
kind: Deployment
metadata:
    name: stg-shopper-deployment
    namespace: shopper
    labels:
        app: shopper
        tier: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: shopper
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 2
            maxUnavailable: 1
    template:
        metadata:
            labels:
                app: shopper
                tier: frontend
        spec:
            containers:
                - image: gcr.io/alfred-302520/stg-shopper-api:0.1
                  #command: ["sleep 600"]
                  imagePullPolicy: IfNotPresent
                  name: shopper
                  resources: 
                    limits:
                      cpu: 1000
                      memory: 1000Mi
                    requests:
                      cpu: 300m
                      memory: 300Mi          
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  envFrom:
                  - configMapRef:
                      name: stg-shopper-config
                  env:
                      - name: SERVER_DBUSER
                        valueFrom:
                            secretKeyRef:
                                name: stg-credentials-shopper
                                key: username
                      - name: SERVER_DBPASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: stg-credentials-shopper
                                key: password
                                         
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 10