apiVersion: v1
kind: Service
metadata:
    name: agenda
    namespace: agenda
    labels:
        app: agenda
        tier: frontend
spec:
    type: NodePort
    ports:
        - port: 3333
    selector:
        app: agenda
        tier: frontend

---

apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
    name: agenda-service-backendconfig
    namespace: agenda
spec:
    timeoutSec: 80000
    connectionDraining:
        drainingTimeoutSec: 3600 # time to complete connections
