apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: agenda-hpa
  namespace: agenda
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agenda-deployment
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70