apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stg-agenda-hpa
  namespace: agenda
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stg-agenda-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70