apiVersion: apps/v1
kind: Deployment
metadata:
    name: stg-agenda-deployment
    namespace: agenda
    labels:
        app: agenda
        tier: frontend
spec:
    replicas: 3
    selector:
        matchLabels:
            app: agenda
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 2
            maxUnavailable: 1
    template:
        metadata:
            labels:
                app: agenda
                tier: frontend
        spec:
            containers:
                - image: gcr.io/alfred-302520/stg-agenda-api@sha256:964df5df7744467cd6a8dc6b86c9e2af607dc7cabbb572a06cd22a16097c0c29
                  #command: ["sleep 600"]
                  imagePullPolicy: IfNotPresent
                  name: agenda
                  resources: 
                    limits:
                      cpu: 1000
                      memory: 1000Mi
                    requests:
                      cpu: 300m
                      memory: 300Mi          
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  envFrom:
                  - configMapRef:
                      name: agenda-config
                  env:
                      - name: SERVER_DBUSER
                        valueFrom:
                            secretKeyRef:
                                name: stg-credentials-agenda
                                key: username
                      - name: SERVER_DBPASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: stg-credentials-agenda
                                key: password
                                         
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 10