apiVersion: v1
kind: Service
metadata:
    name: reset
    namespace: reset
    labels:
        app: reset
        tier: frontend
spec:
    type: NodePort
    ports:
        - port: 8000
    selector:
        app: reset
        tier: frontend

---

apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
    name: stg-reset-service-backendconfig
    namespace: reset
spec:
    timeoutSec: 80000
    connectionDraining:
        drainingTimeoutSec: 3600 # time to complete connections
