apiVersion: apps/v1
kind: Deployment
metadata:
    name: reset-deployment
    namespace: reset
    labels:
        app: reset
        tier: frontend
spec:
    replicas: 3
    selector:
        matchLabels:
            app: reset
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 2
            maxUnavailable: 1
    template:
        metadata:
            labels:
                app: reset
                tier: frontend
        spec:
            containers:
                - image: gcr.io/alfred-302520/pass-reset-api:0.1
                  #command: ["sleep 600"]
                  imagePullPolicy: IfNotPresent
                  name: reset
                  resources: 
                    limits:
                      cpu: 1000
                      memory: 1000Mi
                    requests:
                      cpu: 300m
                      memory: 300Mi          
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  envFrom:
                  - configMapRef:
                      name: reset-config
                  env:
                      - name: SERVER_DBUSER
                        valueFrom:
                            secretKeyRef:
                                name: credentials-reset
                                key: username
                      - name: SERVER_DBPASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: credentials-reset
                                key: password
                                         
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 10
