apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: reset-hpa
  namespace: reset
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reset-deployment
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70