apiVersion: v1
kind: Service
metadata:
    name: backoffice
    namespace: backoffice
    labels:
        app: backoffice
        tier: frontend
spec:
    type: NodePort
    ports:
        - port: 3000
    selector:
        app: backoffice
        tier: frontend

---

apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
    name: backoffice-service-backendconfig
    namespace: backoffice
spec:
    timeoutSec: 80000
    connectionDraining:
        drainingTimeoutSec: 3600 # time to complete connections
