apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backoffice-hpa
  namespace: backoffice
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: backoffice-deployment
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70