apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stg-backoffice-hpa
  namespace: backoffice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stg-backoffice-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70