apiVersion: v1
kind: Service
metadata:
    name: image
    namespace: image
    labels:
        app: image
        tier: frontend
spec:
    type: NodePort
    ports:
        - port: 3200
    selector:
        app: image
        tier: frontend

---

apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
    name: stg-image-service-backendconfig
    namespace: image
spec:
    timeoutSec: 80000
    connectionDraining:
        drainingTimeoutSec: 3600 # time to complete connections
