apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stg-image-hpa
  namespace: image
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stg-image-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70