apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: image-hpa
  namespace: image
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image-deployment
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70