apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: supplier-hpa
  namespace: supplier
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: supplier-deployment
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70