apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stg-supplier-hpa
  namespace: supplier
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stg-supplier-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70