apiVersion: apps/v1
kind: Deployment
metadata:
    name: gestor-deployment
    namespace: gestor
    labels:
        app: gestor
        tier: frontend
spec:
    replicas: 3
    selector:
        matchLabels:
            app: gestor
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 2
            maxUnavailable: 1
    template:
        metadata:
            labels:
                app: gestor
                tier: frontend
        spec:
            containers:
                - image: gcr.io/alfred-302520/gestor-api:0.2
                  #command: ["sleep 600"]
                  imagePullPolicy: IfNotPresent
                  name: gestor
                  resources: 
                    limits:
                      cpu: 1000
                      memory: 1000Mi
                    requests:
                      cpu: 300m
                      memory: 300Mi          
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  envFrom:
                  - configMapRef:
                      name: gestor-config
                  env:
                      - name: SERVER_DBUSER
                        valueFrom:
                            secretKeyRef:
                                name: credentials-gestor
                                key: username
                      - name: SERVER_DBPASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: credentials-gestor
                                key: password
                                         
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 10