apiVersion: v1
kind: Service
metadata:
    name: gestor
    namespace: gestor
    labels:
        app: gestor
        tier: frontend
spec:
    type: NodePort
    ports:
        - port: 8000
    selector:
        app: gestor
        tier: frontend

---

apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
    name: gestor-service-backendconfig
    namespace: gestor
spec:
    timeoutSec: 80000
    connectionDraining:
        drainingTimeoutSec: 3600 # time to complete connections
