apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gestor-hpa
  namespace: gestor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gestor-deployment
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70