apiVersion: v1
kind: Service
metadata:
    name: alfred
    namespace: alfred
    labels:
        app: alfred
        tier: frontend
spec:
    type: NodePort
    ports:
        - port: 8000
    selector:
        app: alfred
        tier: frontend

---

apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
    name: stg-alfred-service-backendconfig
    namespace: alfred
spec:
    timeoutSec: 80000
    connectionDraining:
        drainingTimeoutSec: 3600 # time to complete connections
