apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stg-alfred-hpa
  namespace: alfred
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stg-alfred-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70