apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: alfred-hpa
  namespace: alfred
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: alfred-deployment
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70